# Generated by Django 5.1.3 on 2025-05-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="last_accessed",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
