# Generated by Django 5.2 on 2025-05-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_conversation_last_accessed"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAIAssistant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assistant_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("instructions", models.TextField()),
                ("model", models.CharField(default="gpt-4o", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
