# Generated by Django 5.2 on 2025-05-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_openaithread_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="openaithread",
            name="name",
            field=models.CharField(default="Default Conversation", max_length=255),
            preserve_default=False,
        ),
    ]
