# Generated by Django 5.2 on 2025-05-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_userfiles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openaithread",
            name="id",
        ),
        migrations.AlterField(
            model_name="openaithread",
            name="thread_id",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
