# Generated by Django 5.2 on 2025-05-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_openaithread_thread_id_userfile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="filename",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
