# Generated by Django 5.2 on 2025-05-30 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_userfile_filename_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
