# Generated by Django 5.2 on 2025-05-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_threadmessage_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threadmessage",
            name="id",
            field=models.UUIDField(
                default="<function uuid4 at 0x0000027C69825C60>",
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
