# Generated by Django 5.2 on 2025-05-30 17:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_alter_threadmessage_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threadmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
