# Generated by Django 5.2 on 2025-05-30 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_rename_id_threadmessage_message_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ThreadMessage",
        ),
    ]
