# Generated by Django 5.2 on 2025-05-31 21:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_threadmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="file",
            field=models.FileField(max_length=255, upload_to=api.models.user_file_directory_path),
        ),
    ]
