# Generated by Django 5.2 on 2025-06-01 16:24

import api.models
import storages.backends.s3
import os
from django.db import migrations, models



class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_alter_userfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="file",
            field=models.FileField(
                max_length=255,
                storage=storages.backends.s3.S3Storage(
                    access_key=os.environ.get("AWS_ACCESS_KEY_ID"),
                    bucket_name="study-buddy-app",
                    querystring_auth=False,
                    region_name="us-east-1",
                    secret_key=os.environ.get('AWS_SECRET_ACCESS_KEY'),
                ),
                upload_to=api.models.user_file_directory_path,
            ),
        ),
    ]
