# Generated by Django 5.2 on 2025-06-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_alter_userfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaithread",
            name="last_accessed",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
