# Generated by Django 5.2 on 2025-06-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_alter_openaithread_last_accessed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="last_accessed",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
