# Generated by Django 5.2 on 2025-06-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_alter_userfile_id_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
