# Generated by Django 5.2 on 2025-06-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_embedding_page_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="embedding",
            name="openaiFileId",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
