# Generated by Django 5.2 on 2025-06-23 01:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0028_embedding_openaifileid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="embedding",
            old_name="openaiFileId",
            new_name="openai_file_id",
        ),
    ]
