# Generated by Django 5.2 on 2025-06-24 18:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0029_rename_openaifileid_embedding_openai_file_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chunk_number", models.IntegerField()),
                ("text", models.CharField(max_length=5000)),
                ("embedding", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="api.userfile",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Embedding",
        ),
    ]
