# Generated by Django 5.2 on 2025-06-24 21:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_chunk_delete_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="file",
            field=models.FileField(
                max_length=255,
                storage=api.models.MediaStorage(),
                upload_to=api.models.user_file_directory_path,
            ),
        ),
    ]
