# Generated by Django 5.2 on 2025-06-24 22:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0031_alter_userfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="file",
            field=models.FileField(
                max_length=255, upload_to=api.models.user_file_directory_path
            ),
        ),
    ]
