# Generated by Django 5.2 on 2025-06-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_alter_userfile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaithread",
            name="last_accessed",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
